services:
  cup:
    image: ghcr.io/sergi0g/cup:latest
    container_name: cup
    # Read-only Docker API via /services/docker-proxy.
    extends:
      file: ../docker-proxy/profiles.yaml
      service: docker-read
    restart: unless-stopped
    command: -s tcp://docker-proxy:2375 -c /config/cup.json serve
    volumes:
      - ./cup.json:/config/cup.json
    networks:
      - caddy
    labels:
      caddy: "*.alpenglow.acbc.house"
      caddy.@cup.host: "cup.alpenglow.acbc.house"
      caddy.reverse_proxy: "@cup {{upstreams http 8000}}"

networks:
  caddy:
    external: true
  docker-proxy:
    external: true
