services:
  caddy:
    build: .
    container_name: caddy
    env_file: .env
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      - caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "10443:10443"
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
      - /var/run/docker.sock:/var/run/docker.sock

  caddy-edge:
    build: .
    container_name: caddy-edge
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./edge.Caddyfile:/etc/caddy/Caddyfile
    command: caddy run --config /etc/caddy/Caddyfile 

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy:
    external: true 
