services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    env_file: .env
    environment:
      HOMEPAGE_ALLOWED_HOSTS: acbc.house
    volumes:
      - ./config:/app/config
    labels:
      caddy: acbc.house
      caddy.reverse_proxy: "{{upstreams http 3000}}"
    networks:
      - caddy

networks:
  caddy:
    external: true
