#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-proxy:
    image: alangrainger/immich-public-proxy:latest
    container_name: immich_public_proxy
    restart: always
    expose:
      - "3000"
    labels:
      caddy_0: "*.acbc.house"
      caddy_0.@photos-share.host: "photos-share.acbc.house"
      caddy_0.reverse_proxy: "@photos-share {{upstreams http 3000}}"
      caddy_1: "*.acbc.house:10443"
      caddy_1.@photos-share.host: "photos-share.acbc.house"
      caddy_1.reverse_proxy: "@photos-share {{upstreams http 3000}}"
    networks:
      - caddy
    environment:
      PUBLIC_BASE_URL: https://photos-share.acbc.house
      IMMICH_URL: http://immich_server:2283

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    expose:
      - "8081"
      - "8082"
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ./immich.json:/opt/immich/config.json
    env_file:
      - .env
    networks:
      - caddy
      - postgres
      - default
    depends_on:
      - redis
    user: 108:112
    restart: always
    healthcheck:
      disable: false
    labels:
      caddy: "*.acbc.house"
      caddy.@photos.host: "photos.acbc.house"
      caddy.reverse_proxy: "@photos {{upstreams http 2283}}"

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    networks:
      - default
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571 
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - default

volumes:
  model-cache:

networks:
  caddy:
    external: true
  postgres:
    external: true
  default:
    driver: bridge
