services:
  uptime:
    container_name: uptime_kuma
    image: louislam/uptime-kuma:2
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    labels:
      caddy_0: "*.alpenglow.acbc.house"
      caddy_0.@uptime.host: "uptime.alpenglow.acbc.house"
      caddy_0.reverse_proxy: "@uptime {{upstreams http 3001}}"
      caddy_1: "*.alpenglow.acbc.house:10443"
      caddy_1.@uptime.host: "uptime.alpenglow.acbc.house"
      caddy_1.@uptime.path: "/status /status/ /assets/* /api/status-page/*"
      caddy_1.reverse_proxy: "@uptime {{upstreams http 3001}}"
    networks: 
      - caddy

networks:
  caddy:
    external: true
