services:
  immichframe: 
    restart: always 
    image: ghcr.io/immichframe/immichframe:dev.3rob3.autorefreshonerror
    environment:
      TZ: America/Denver
      LOG_LEVEL: Debug
    volumes:
      - ./config:/app/Config
    networks:
      - caddy
    labels:
      caddy: "*.internal.acbc.house"
      caddy.@immichframe.host: "immichframe.internal.acbc.house"
      caddy.reverse_proxy: "@immichframe {{upstreams http 8080}}"

networks:
  caddy:
    external: true
