# not actually YAML but lets pretend:
# -*- mode: yaml -*-
# vim: ft=yaml:

[global]
e2dsa  # enable file indexing and filesystem scanning
e2ts   # enable multimedia indexing
ansi   # enable colors in log messages

# enable IdP support by expecting username in
# http-headers provided by the reverse-proxy; header "X-IdP-User"
# will contain the username
idp-h-usr: x-forwarded-preferred-username
idp-h-grp: x-forwarded-groups
rproxy: -2

xff-src: 10.0.0.0/16

[/share]
  /srv/share
  accs:
    rwd: *

[/u/${u}]
  /srv/users/${u}
  accs:
    rwmda: ${u}
