services:
  web_recipes:
    restart: always
    image: vabene1111/recipes
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    networks:
      - caddy
      - postgres
      - ai
    labels:
      caddy_0: "*.acbc.house"
      caddy_0.@recipes.host: "recipes.acbc.house"
      caddy_0.reverse_proxy: "@recipes {{upstreams http 80}}"
      caddy_1: "*.acbc.house:10443"
      caddy_1.@recipes.host: "recipes.acbc.house"
      caddy_1.reverse_proxy: "@recipes {{upstreams http 80}}"

volumes:
  nginx_config:
  staticfiles:

networks:
  caddy:
    external: true
  postgres:
    external: true
  ai:
    external: true
