services:
  web_recipes:
    restart: always
    image: vabene1111/recipes
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    networks:
      - caddy
      - postgres
    labels:
      caddy: "*.acbc.house"
      caddy.@recipes.host: "recipes.acbc.house"
      caddy.reverse_proxy: "@recipes {{upstreams http 80}}"

volumes:
  nginx_config:
  staticfiles:

networks:
  caddy:
    external: true
  postgres:
    external: true
